In [7]:
import torch

a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

print("a = ", a)
print("b = ", b)

# 维度一样的 2 个张量, 就算是 Shape 不一样, 也能相加
# 因为会自动拓展成, 多的那个
print("a+b = ", a+b)

a = torch.arange(6).reshape((3, 2))
b = torch.arange(6).reshape((2, 3))

print("a = ", a)
print("b = ", b)
# 这种情况会直接报错, 因为没法通过 复制 来进行广播
# print("a+b = ", a+b)


a =  tensor([[0],
        [1],
        [2]])
b =  tensor([[0, 1]])
a+b =  tensor([[0, 1],
        [1, 2],
        [2, 3]])
a =  tensor([[0, 1],
        [2, 3],
        [4, 5]])
b =  tensor([[0, 1, 2],
        [3, 4, 5]])


In [12]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3,4))

# 取特定的行
print(X[-1])
print(X[1:3])

# 通过坐标来写值
X[1, 2] = 9
print(X)

# 多处赋值
X[0:2, :] = 12
print(X)


tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [28]:
import torch

X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# 这种操作, 会导致一次拷贝, 比较耗
before = id(Y)
Y = Y + X
print(id(Y) == before)

# : 表示逐元素的赋值操作, 这样会节省内存
Y2 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before2 = id(Y2)
Y2[:] = Y2+X
print(id(Y2) == before2)

# 当然更简单的一种形式就是 +=
Y3 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before3 = id(Y3)
Y3 += X
print(id(Y3) == before3)

False
True
True


In [32]:
import torch

# 支持跟 numpy 的转换
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
A = X.numpy()
B = torch.tensor(A)
print(type(A))
print(type(B))

# 支持基础数据类型的转换
a = torch.tensor([3.5])
print(a, a.item(), float(a), int(a))


<class 'numpy.ndarray'>
<class 'torch.Tensor'>
tensor([3.5000]) 3.5 3.5 3
