In [8]:
import torch

a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
print(a) # reshape 这里指向的数据是一样的

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])


In [7]:
import torch

a = torch.arange(12)
b = a.view((3,4))
b[:] = 2
print(a) # reshape 这里指向的数据是一样的

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])


In [19]:
a = torch.arange(9).reshape(3,3)
b = a.permute(1,0)
c = b.reshape(9)
c[:] = 2
# 如果在内存中做了处理, c 在 b 调用 reshape 时就会生成一个新的 张量
a,b,c

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 3, 6],
         [1, 4, 7],
         [2, 5, 8]]),
 tensor([2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [24]:
a = torch.arange(9).reshape(3,3)
b = a.permute(1,0)
c = b.view((3,3))
c[:] = 2
# 如果在内存中做了处理, c 在 b 调用 reshape 时就会生成一个新的 张量
a,b,c

(tensor([[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]),
 tensor([[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]),
 tensor([[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]))